import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const sql of fs.readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(sql.trim())sqlite.exec(sql);
function prepare(sql){let values=[];return {bind(...v){values=v;return this},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return {results:sqlite.prepare(sql).all(...values)}},run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}}}};}
const env={DB:{prepare,async batch(statements){sqlite.exec('BEGIN');try{const rows=statements.map(s=>s.run());sqlite.exec('COMMIT');return rows;}catch(e){sqlite.exec('ROLLBACK');throw e;}}}};
const users={admin:['owner','subsubanjr.eduardo@gmail.com'],buyer:['buyer','buyer@example.com'],other:['other','other@example.com']};
async function call(path,method='GET',body,who='buyer'){const u=users[who];const r=await worker.fetch(new Request('https://store.test'+path,{method,headers:{...(u?{'oai-authenticated-user-id':u[0],'oai-authenticated-user-email':u[1]}:{}),...(body?{'Content-Type':'application/json',Origin:'https://store.test'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json()};}
const admin=()=>call('/api/admin/store','GET',null,'admin');
assert.equal((await call('/api/admin/store','GET',null,'other')).status,403);
let a=(await admin()).data;assert.equal(a.data.products.length,6);let p=a.data.products[0],v=p.variants[0];assert.equal(v.stock,0);
assert.equal((await call('/api/admin/inventory','POST',{revision:a.revision,productId:p.id,variantId:v.id,action:'set',quantity:2,reason:'Opening stock'},'admin')).status,200);
assert.equal((await call('/api/admin/settings','POST',{revision:a.revision,settings:a.data.settings},'admin')).status,409);
a=(await admin()).data;p=a.data.products[0];p.salePrice=999;p.regularPrice=1299;
assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,product:p},'admin')).status,200);
const customer={name:'Buyer',phone:'09000000000',email:'buyer@example.com',address:'Test address',city:'Claveria',postal:'9004'};
const payload=()=>({requestKey:crypto.randomUUID(),customer,payment:'GCash',items:[{id:p.id,color:v.color,size:v.size,qty:2,price:999}],total:1998});
const bad=payload();bad.items[0].price=1;assert.equal((await call('/api/orders','POST',bad)).status,409);
const b=payload();const results=await Promise.all([call('/api/orders','POST',b),call('/api/orders','POST',payload(),'other')]);assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(results.filter(r=>r.status===409).length,1);
const saved=results.find(r=>r.status===201).data;
assert.equal((await call('/api/orders','POST',b)).data.id,saved.id);
a=(await admin()).data;assert.equal(a.data.products[0].variants[0].stock,0);
assert.equal((await call('/api/store')).data.products[0].purchasable,false);
let orders=(await call('/api/admin/orders','GET',null,'admin')).data.orders;assert.equal(orders.length,1);assert.equal(orders[0].total,1998);assert.equal(orders[0].items[0].price,999);
p=a.data.products[0];p.salePrice=899;assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,product:p},'admin')).status,200);
assert.equal((await call('/api/account')).data.orders[0].items[0].price,999);
assert.equal((await call('/api/account','GET',null,'other')).data.orders.length,0);
const cancel={revision:0,status:'Cancelled',payment_status:'Unpaid',tracking:'',notes:'Customer cancelled'};
assert.equal((await call('/api/admin/orders/'+saved.id,'PATCH',cancel,'admin')).status,200);
assert.equal((await call('/api/admin/orders/'+saved.id,'PATCH',cancel,'admin')).status,409);
assert.equal((await admin()).data.data.products[0].variants[0].stock,2);
assert.equal((await call('/api/admin/orders/'+saved.id,'PATCH',{...cancel,revision:1},'admin')).status,200);
assert.equal((await admin()).data.data.products[0].variants[0].stock,2);
assert.equal((await call('/api/admin/inventory','GET',null,'admin')).data.logs.length,3);
a=(await admin()).data;p=a.data.products[0];p.preorder=true;assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,product:p},'admin')).status,200);
a=(await admin()).data;a.data.settings.preordersEnabled=false;a.data.settings.payments=[];a.data.settings.hero.heading='Updated by admin';
assert.equal((await call('/api/admin/settings','POST',{revision:a.revision,settings:a.data.settings},'admin')).status,200);
assert.equal((await call('/api/store')).data.settings.hero.heading,'Updated by admin');assert.equal((await call('/api/store')).data.products[0].purchasable,false);
assert.equal((await call('/api/orders','POST',payload())).status,400);
a=(await admin()).data;assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,action:'archive'},'admin')).status,200);assert.equal((await call('/api/store')).data.products.some(x=>x.id===p.id),false);
a=(await admin()).data;assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,action:'restore'},'admin')).status,200);assert.equal((await admin()).data.data.products[0].status,'draft');
a=(await admin()).data;assert.equal((await call('/api/admin/products','POST',{revision:a.revision,id:p.id,action:'duplicate'},'admin')).status,200);assert.equal((await admin()).data.data.products.length,7);assert.equal((await admin()).data.data.products.at(-1).variants[0].stock,0);
const review={rating:5,title:'Great hoodie',body:'Great material and comfortable fit.'};assert.equal((await call('/api/products/white-hoodie/reviews','POST',review)).status,201);assert.equal((await call('/api/products/white-hoodie/reviews')).data.summary.count,1);
assert.equal((await call('/api/admin/media','POST',{data:'x'},'admin')).status,503);
console.log('PASS: admin authorization, CMS edits, variant stock, stale saves, concurrent checkout, immutable paid prices, idempotent orders, cancellation restoration, private order history, archive/restore/duplicate, payment/preorder settings, reviews and missing-media handling.');
